#!/usr/bin/python3
"""Module that defines the Base class.

This module provides the Base class, which manages the id attribute
for all its subclasses and provides shared JSON serialization,
deserialization, and file persistence logic.
"""
import json


class Base:
    """Base class that manages id attribute for all future classes."""

    __nb_objects = 0

    def __init__(self, id=None):
        """Initialize a new Base instance.

        Args:
            id: the id to assign to this instance. If None, a new id
                is generated by incrementing the private class
                counter __nb_objects.
        """
        if id is not None:
            self.id = id
        else:
            Base.__nb_objects += 1
            self.id = Base.__nb_objects

    @staticmethod
    def to_json_string(list_dictionaries):
        """Return the JSON string representation of a list of dicts.

        Args:
            list_dictionaries: a list of dictionaries.

        Returns:
            The JSON string representation of list_dictionaries, or
            "[]" if list_dictionaries is None or empty.
        """
        if list_dictionaries is None or len(list_dictionaries) == 0:
            return "[]"
        return json.dumps(list_dictionaries)

    @classmethod
    def save_to_file(cls, list_objs):
        """Write the JSON string representation of list_objs to a file.

        The filename used is <cls.__name__>.json.

        Args:
            list_objs: a list of instances that inherit from Base.
        """
        filename = "{}.json".format(cls.__name__)
        if list_objs is None:
            list_objs = []
        list_dicts = [obj.to_dictionary() for obj in list_objs]
        with open(filename, "w") as f:
            f.write(cls.to_json_string(list_dicts))

    @staticmethod
    def from_json_string(json_string):
        """Return the list represented by a JSON string of dictionaries.

        Args:
            json_string: a string representing a list of dictionaries.

        Returns:
            The list represented by json_string, or an empty list if
            json_string is None or empty.
        """
        if json_string is None or len(json_string) == 0:
            return []
        return json.loads(json_string)

    @classmethod
    def create(cls, **dictionary):
        """Return an instance of cls with all attributes already set.

        Args:
            dictionary: key/value pairs of attributes to set on the
                new instance.

        Returns:
            A new instance of cls with attributes set from dictionary.
        """
        if cls.__name__ == "Rectangle":
            dummy = cls(1, 1)
        else:
            dummy = cls(1)
        dummy.update(**dictionary)
        return dummy

    @classmethod
    def load_from_file(cls):
        """Return a list of instances loaded from <cls.__name__>.json.

        Returns:
            A list of instances of cls, or an empty list if the file
            <cls.__name__>.json doesn't exist.
        """
        filename = "{}.json".format(cls.__name__)
        try:
            with open(filename, "r") as f:
                list_dicts = cls.from_json_string(f.read())
        except IOError:
            return []
        return [cls.create(**d) for d in list_dicts]
